name: Build and Package

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET environment
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.x'

      - name: Restore NuGet packages
        run: nuget restore calculator-project.sln

      - name: Build project
        run: msbuild /p:Configuration=Release YourProject.csproj

      - name: Package artifact
        run: |
          # Replace this with the command to package your artifact
          # For example, creating an installer or copying files to a directory
          # Example: dotnet publish -c Release -o publish/
          # Example: cp -r YourProject/bin/Release/* publish/
          echo "Package your artifact here"

    # Upload the MSIX package: https://github.com/marketplace/actions/upload-a-build-artifact
   - name: Upload build artifacts
    uses: actions/upload-artifact@v3
    with:
        name: MSIX Package
        path: ${{ env.Wap_Project_Directory }}/AppPackages

